package com.robinrehbein.beveldevil.game

/** UI strings. */
object Txt {
    val play = T("PLAY", "SPIELEN")
    val album = T("ALBUM", "ALBUM")
    val soundOn = T("SOUND ON", "TON AN")
    val soundOff = T("SOUND OFF", "TON AUS")
    val tap = T("Tap to boot", "Tippen zum Booten")
    val soon = T("SOON", "BALD")
    val new = T("new", "neu")
    val pause = T("PAUSE", "PAUSE")
    val resume = T("RESUME", "WEITER")
    val restart = T("RESTART", "NEU STARTEN")
    val levels = T("LEVELS", "LEVELS")
    val cleared = T("CLEARED!", "GESCHAFFT!")
    val next = T("NEXT", "WEITER")
    /** Banner when Mephi deals another round in the same room. */
    val rematch = T("REMATCH!", "REVANCHE!")
    val newHand = T("NEW HAND", "NEUES BLATT")
    val round = T("ROUND", "RUNDE")
    val deaths = T("DEATHS", "TODE")
    val best = T("BEST", "BESTWERT")
    val trap = T("TRAP", "FALLE")
    val bluff = T("BLUFF", "BLUFF")
    val albumTitle = T("DEVIL CARDS", "TEUFELSKARTEN")
    val caught = T("crashed you %d×", "%d× abgestürzt")
    val soulsSacrificed = T("SOULS SACRIFICED", "SEELEN GEOPFERT")
    val tapCard = T("Tap a card to inspect it.", "Tippe eine Karte an.")
    val endTitle = T("PROCESS KILLED.", "PROZESS BEENDET.")
    val endSub = T("Bevel pulled the plug. The net is back.", "Bevel zog den Stecker. Das Netz lebt.")
    val endQuote = T("Restart scheduled for next boot.", "Neustart beim nächsten Booten.")
    val endDeaths = T("Total deaths: %d", "Tode insgesamt: %d")
    val toTitle = T("TITLE", "ZUM TITEL")
    val settings = T("SETTINGS", "EINSTELLUNGEN")
    val controls = T("CONTROLS", "STEUERUNG")
    val schemeButtons = T("BUTTONS", "TASTEN")
    val schemeStick = T("STICK", "STICK")
    val btnSize = T("BUTTON SIZE", "TASTENGRÖSSE")
    val haptics = T("HAPTICS", "VIBRATION")
    val sound = T("SOUND", "TON")
    val music = T("MUSIC", "MUSIK")
    val leftHanded = T("LEFT-HANDED", "LINKSHÄNDER")
    val tilt = T("TILT SENSOR", "NEIGUNG")
    val on = T("ON", "AN")
    val off = T("OFF", "AUS")
    val skip = T("SKIP", "ÜBERSPRINGEN")
    val story = T("STORY", "STORY")
    val tapContinue = T("Tap to continue", "Tippen: weiter")
    val tapDescend = T("Tap to descend", "Tippen zum Absteigen")
    val noAds = T("NO ADS", "OHNE WERBUNG")
    val skipLevel = T("SKIP LEVEL", "LEVEL ÜBERSPRINGEN")
    val skipAd = T("SKIP: WATCH AD", "SKIP: WERBUNG")
    val adLoading = T("AD LOADING...", "WERBUNG LÄDT...")
    val adChoices = T("AD CHOICES", "WERBE-WAHL")
    val worldNo = T("WORLD %d", "WELT %d")
}
